# Generated by Django 3.1.2 on 2020-10-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShelterRegisterData',
            fields=[
                ('shelter_id', models.AutoField(primary_key=True, serialize=False)),
                ('shelter_email', models.EmailField(max_length=254, unique=True)),
                ('shelter_name', models.CharField(max_length=80)),
                ('shelter_address', models.CharField(max_length=200)),
                ('shelter_city', models.CharField(max_length=50)),
                ('shelter_state', models.CharField(max_length=50)),
            ],
        ),
    ]
