# Generated by Django 3.1.2 on 2020-12-01 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playdate", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientuserpet",
            name="pet_playdate_day1",
            field=models.CharField(default="Friday", max_length=50),
        ),
        migrations.AddField(
            model_name="clientuserpet",
            name="pet_playdate_time1",
            field=models.CharField(default="Night", max_length=50),
        ),
    ]
