# Generated by Django 3.1.2 on 2020-12-01 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playdate", "0002_auto_20201201_0315"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientuserpet",
            name="pet_spayneuter",
            field=models.CharField(default="Yes", max_length=50),
        ),
    ]
