# Generated by Django 3.1.2 on 2020-11-10 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="latitude",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="user",
            name="longitude",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
