# Generated by Django 3.1.2 on 2020-11-11 17:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_auto_20201110_0323"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="favorite",
            field=models.ManyToManyField(
                blank=True, related_name="favorite", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
