# Generated by Django 3.1.2 on 2020-11-08 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_auto_20201107_2254"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="shelterRegisterData",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pet",
                to="accounts.shelterregisterdata",
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
