# Generated by Django 3.1.2 on 2020-11-04 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201104_0127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='id',
            new_name='email',
        ),
    ]
