# Generated by Django 3.1.2 on 2020-11-04 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201104_0131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='email',
            new_name='id',
        ),
    ]
