# Generated by Django 3.1.2 on 2020-12-08 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_auto_20201207_0219"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="about",
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
