# Generated by Django 3.1.2 on 2020-11-04 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201104_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_age',
            field=models.CharField(max_length=10),
        ),
    ]
