# Generated by Django 3.1.2 on 2020-11-04 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_auto_20201104_0158"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pet",
            name="pet_id",
        ),
    ]
